server:
  port: 1000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: router01
          uri: http://msclient-rec-id:8181
          predicates:
            - Path=/client/**
        - id: router02
          uri: http://msdebitcard-rec:8282
          predicates:
            - Path=/debitcard/**            
