server: 
  port: 8181
spring:
  application:
    name: ms-client
  data:
    mongodb:
      uri: mongodb+srv://amigoprogramador:Evangelion2939.@clusterap.67x9fq9.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp
      database: clientdb

  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /api-docs

    
management:
  endpoint:
    health:
      probes:
        enabled: true
