server: 
  port: 8081
spring:
  application:
    name: ms-client
  data:
    mongodb:
      uri: mongodb+srv://amigoprogramador:Evangelion2939.@clusterap.67x9fq9.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp
      database: clientdb
springdoc:
  api-docs:
    path: /api-docs
