server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb+srv://amigoprogramador:Evangelion2939.@clusterap.67x9fq9.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp
      database: debitcarddb
springdoc:
  api-docs:
    path: /api-docs
application:
  third:
    app:
      msclient: http://localhost:8080/client